server:
  port: 9000
spring:
  application:
    name: spring-cloud-api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "GET, POST, PUT, DELETE"
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:eurekaserver}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true




