server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://mysqlservice:3306/blog_db?createDatabaseIfNotExist=true
    username: root
    password: 9818101977
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  application:
    name: blog-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:eurekaserver}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true
