FROM openjdk
WORKDIR usr/src
ADD ./target/NewsServiceApplication-0.0.1-SNAPSHOT.jar /usr/src/NewsServiceApplication-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","NewsServiceApplication-0.0.1-SNAPSHOT.jar"]
