server:
  port: 8086
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://mongodbservice:27017/news_db}
  application:
    name: news-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:eurekaserver}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true
